### PR TITLE
added jwt authentication middleware

### PR DESCRIPTION
**Pull request by StephanDollberg**
This PR adds a middleware for Json-Web-Token authentication (JWT). I use the [jwt-go](https://github.com/dgrijalva/jwt-go) package for the jwt implementation. I don't know what your stance on third-party packages is as I think this would be the first one. 

I have mirrored the rest to be in line with the basic auth middleware.

If you like this we can expand it by adding more signing algorithms and adding a refresh option. Also, I can add an [example](https://gist.github.com/StephanDollberg/b99dbbf3620b70cc0f0d) to the readme.

Looking forward to hear your feedback!

### CODE REVIEW

**Comment by ant0ine** [comment]
Hi!

That looks great! Thanks for including the unit tests!

A few thoughts about the middlewares in general, and third party ones in particular.

1) I don't really like the current middleware names: `xxxMiddleware`. Instead of the `Middleware` suffix, I'm planning to move the middlewares in a subpackage (same repo) named `middlewares`. 
```go
// That'll give us
api.Use(middlewares.Gzip{})
// instead of
api.Use(rest.GzipMiddleware{})
``` 
This change was not possible as part of the v3, because of package circular dependencies. When ResourceHandler will be retired, that circular dependency will go away, and this change will become possible.
=> Probably v4. Nothing urgent anyway, this is only cosmetic.

2) Go-Json-Rest dependencies. So far this framework depends only on the standard lib, no other dependencies. I'd like to keep this package lightweight: the machinery to assemble the middlewares and a few core middlewares that are required for most application. All this not relying on third party packages.

3) Examples. There are a few examples that are similar to JWTMiddleware. They provide the middleware as part of the code of the example, and rely on a third party package for most of the implementation. See "Statsd" and "NewRelic". These examples are a good start, but the middleware is reusable by copy paste only, and there is no unit tests.

Given all this, here is my suggestion:

How about:
1) creating your own repo named something like go-json-rest-middleware-jwt under your github account.
2) checking in it your code and unit tests
3) submit a PR to go-json-rest-examples with a simple example depending on go-json-rest-middleware-jwt

On my side I will:
1) add a new section in the go-json-rest README, to explain this contribution process, and list the contribution and contributor repositories.
2) regenerate the go-json-rest README to include the new example.
3) extract the Statsd and NewRelic middlewares to their own repo, to follow the same pattern.

Let me know what you think and if that works for you,

Antoine

**Comment by ant0ine** [comment]
To get a sense of how it looks, I created the Statsd repo here: https://github.com/ant0ine/go-json-rest-middleware-statsd and updated the examples and README.

**Comment by StephanDollberg** [comment]
Yeah, sounds all very good.

While I am generally not a big fan of splitting everything up to certain places, the awesome go dependency system makes that hardly an issue. 

However, two possible alternatives came to my mind to better group additional tools:

 - (Use a github organization to group them. Probably not a good idea as contributors would first have to join the organization.)
 - Create one repo that contains additional middlewares(and maybe other stuff) but which might rely on third party packages or are not considered as stable as the core part. This would seem similar to something like `golang.org/x`.

Cheers,
Stephan

**Comment by ant0ine** [comment]
Cool!

Re github org: That seems a bit overkill for now. Maybe in the future.

Re one repo: I thought about creating go-json-rest-contrib as a way to group third party middlewares. But repositories that are a collection of things are not easy to manage, versioning is difficult. Stating which ones are production ready for instance, that could be a mess :-)  I prefer having individual repos and linking them from various README and documentations.

Antoine

**Comment by StephanDollberg** [comment]
Great, then let's close this and I will create a PR to the examples repo once I have setup the jwt-repo (I will probably add refresh functionality first, though).

**Comment by ant0ine** [comment]
There is now a place in the README where to list the middlewares:
https://github.com/ant0ine/go-json-rest#middlewares

**Comment by StephanDollberg** [comment]
Ok, should I also manually add the example there or do you auto-generate it from the example repo?

**Comment by ant0ine** [comment]
Examples are auto inserted in the README from the go-json-rest-examples repo. It just needs a directory with a README and main.go.

**Comment by StephanDollberg** [comment]
Ok, a final thing I am now wondering about. Should the middleswares also use rest as a package name or something different?

**Comment by ant0ine** [comment]
The name of the package will be the last token of the import "path". So for instance if you put the go files at the root of "go-json-rest-middleware-jwt", then the package name will be "jwt". I think it's fine for each third party middleware to have its own package name. Actually, it's best to not pick "rest", as it won't be the same "rest" as go-json-rest, and that will be confusing.

**Pull request closed without merging**
