### PR TITLE
Minor change to the test package name

### PR DESCRIPTION
**Pull request by domthinks**
Minor change to allow vim-go to appropriately locate the package github.com/ant0ine/go-json-rest/rest/test

### CODE REVIEW

**Comment by ant0ine** [comment]
Interesting, but this is a breaking change. So, I tagged it with "v4 idea"

**Comment by domthinks** [comment]
@ant0ine 
Out of curiosity what makes this a breaking change? 
Also, do you have any suggestions on how to make this a non-breaking change? 

Thanks,
-Dom

**Comment by ant0ine** [comment]
@domthinks "test" is a public package used by developers to test their APIs. Changing the name of the package would break their code.

**Comment by domthinks** [comment]
I'm gonna close this PR since it's a breaking change.

**Pull request closed without merging**
