### PR TITLE
Simplified version of routes api

### PR DESCRIPTION
**Pull request by saromanov**
Hi!
I've just made simple version of Routes api. In the example with countries it will be looks like:
```go
router, err := rest.MakeRouterSimply(
        rest.Get{"/countries", GetAllCountries},
        rest.Post{"/countries", PostCountry},
        rest.Get{"/countries/:code", GetCountry},
        rest.Delete{"/countries/:code", DeleteCountry},
    )
```
Current version is:
```go
router, err := rest.MakeRouter(
        &rest.Route{"GET", "/countries", GetAllCountries},
        &rest.Route{"POST", "/countries", PostCountry},
        &rest.Route{"GET", "/countries/:code", GetCountry},
        &rest.Route{"DELETE", "/countries/:code", DeleteCountry},
    )
```
In the result, its just a high level version on current api. In my point of view, it looks more pretty, but what do you think about that?

### CODE REVIEW

**Comment by ant0ine** [comment]
Hi

Thanks for your pull request!
I was tempted to offer these kinds of shortcuts to create routes as part of the v3. And I resisted this idea for a few reasons:

* I think that having a Route object is important. Before passing the routes to the router, you can keep references to them, and then use methods on them. For instance the method MakePath(...) offers the ability to do reverse route resolution (ie: generate the path from the route and the parameters). There is no good reason to make Get, Post, Put, Delete distinct objects. One possible solution would be to provide these shortcuts with functions instead of types. eg: `func Get(PathExp string, Func HandlerFunc) *Route`. 

* The HTTP protocol does not defined the HTTP methods, these are conventions, widely adopted, but conventions. In the case of a REST API, GET, PUT, POST, DELETE are the standard, but others can be used too. OPTIONS for CORS request, or for load balancing preconnect. HEAD could make sense too. And who knows what else. I feel like the user is better off choosing the HTTP method, at the cost of typing a string.

Antoine

**Comment by wingyplus** [comment]
I think make it as a function. example

```go
func Get(pathExp string, fn HandlerFunc) *Route { 
        return &Route{ "GET", pathExp, fn}
}
```

**Comment by saromanov** [comment]
ok, 
* Yes, you right, my solution not supported MakePath(..), its just a structure. With solution with functions it works. And even no need to use addition function MakeRouterSimply(..) It works with MakeRouter. It looks more nice.
``` go
router, err := rest.MakeRouter(
        rest.Get("/countries", GetAllCountries),
    )
```
* This is not replacement of current API, its just a shortcut and will be useful only for standrad REST API. Of course, for non standard, you need to use standard way 

```go  
&rest.Route{"NON_STANDARD", "/countries", GetAllCountries}
 ```
But ok, i understand your point:)

**Comment by ant0ine** [comment]
@saromanov @wingyplus I've tried that solution in this PR https://github.com/ant0ine/go-json-rest/pull/139

I think it makes the code more readable. And it also fixes a problem with **golint** that @yannk reported a while ago. (golint wants the keys to be explicit in the literal definitions. With these methods, it's shorter, and won't trigger the linting errors)

Let me know what you think.

Antoine

**Comment by ant0ine** [comment]
Corresponding PR for the examples is here: https://github.com/ant0ine/go-json-rest-examples/pull/11

**Comment by ant0ine** [comment]
https://github.com/ant0ine/go-json-rest/pull/139 has been merged, closing this one.

**Pull request closed without merging**
